# Generated by Django 5.1.7 on 2025-12-19 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('holati', models.BooleanField(default=True)),
                ('talaba_qoshilgan_sana', models.DateField(blank=True, null=True)),
                ('faollashtirilgan', models.BooleanField(default=False)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('guruh_boyicha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Oqituvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('balans', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiqdorTahrirlash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sana', models.DateField()),
                ('izoh', models.TextField(blank=True, null=True)),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guruh')),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='talabalar/')),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('balans', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mashgulot_sanalari', models.TextField(blank=True, null=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('oqituvchilar', models.ManyToManyField(blank=True, to='api.oqituvchi')),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.talaba')),
            ],
        ),
        migrations.CreateModel(
            name='QongiroqTarixi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.talaba')),
            ],
        ),
        migrations.CreateModel(
            name='LidTarixi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holat', models.CharField(max_length=100)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.talaba')),
            ],
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izohlar', to='api.talaba')),
            ],
        ),
        migrations.CreateModel(
            name='Eslatma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=200)),
                ('izoh', models.TextField(blank=True, null=True)),
                ('sana', models.DateTimeField()),
                ('xodim', models.CharField(max_length=100)),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.talaba')),
            ],
        ),
        migrations.CreateModel(
            name='TalabaGuruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guruh')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.talaba')),
            ],
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tolov_usuli', models.CharField(choices=[('naqd', 'Naqd pul'), ('plastik', 'Plastik karta'), ('bank', 'Bank hisobi'), ('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum'), ('humo', 'Humo')], max_length=20)),
                ('sana', models.DateField()),
                ('izoh', models.TextField(blank=True, null=True)),
                ('guruh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.guruh')),
                ('talaba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.talaba')),
            ],
        ),
        migrations.CreateModel(
            name='TolovQaytarish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('tolov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tolov')),
            ],
        ),
    ]
